# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- binary: bin/terradays
  main: ./main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.version={{.Version}}
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^refactor:'
